### ISSUE TITLE
Would you open dxsurvey website source code ?

### ISSUE THREAD

**Issue by Restry** [andrewtelnov/surveyjs#32]
Hi andrewtelnov , your surveyjs it's really cool and useful for me . I have a lot of requirements same with dxsurvey website  https://dxsurvey.com 
Thanks

**Comment by andrewtelnov** [comment]
Hi,
At first thank you for using surveyjs library.

About dxsurvey.com. Unfortunately, I do not want to make it open source, since maybe this service will not be free in the future.
It is very likely, it will be developed by a small team, not only by me.
What additional features do you need from the service? I may consider to implement them.

About service code, there nothing fancy here so far:
1) open web api to store/get survey data - you can do it in several lines of code.
2) web api with authorization support for manipulating surveys. 
3) UI for displaying/modifying the surveys and their data.

Everything is pretty strightforward. I am sure, you will be able to find all the needed examples in the web. How to work with JSON data and so on.

Thank you,
Andrew

**Comment by Restry** [comment]
it's okay  , i'll keep watching this project . thanks
