### ISSUE TITLE
showQuestionNumbers = off leaves a dot before the question title

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#58]
I cannot completely switch off the questions numbers. There is a dot that remains before the question title.

**Comment by andrewtelnov** [comment]
Yes, there is a bug in the current version. However, It is fixed in the source: https://github.com/andrewtelnov/surveyjs/issues/48
It will go away after creating a new version  0.9.11 (the current version is  0.9.11).
You may build the library from sources, following the instruction in [readme.md file](https://github.com/andrewtelnov/surveyjs)

Thank you,
Andrew
