### ISSUE TITLE
Validation errors not highlighted any more

### ISSUE THREAD

**Issue by mattes3** [andrewtelnov/surveyjs#76]
Please see https://justaskusers.herokuapp.com/quote/new/
If you simply click on "next" without answering any questions, the validation error is not displayed in red but in black.
In V0.9.10, this was still OK.

**Comment by andrewtelnov** [comment]
Yes, you are right. I have merged bootstrap and standard errors template and did not do it 100% correct.
I have fixed the bug. 
The css.error.item style were applied to error title. Title doesn't used in the standard version. It shows alert icon in bootstrap. I have introduced a new style, css.error.icon and apply styles correctly. You may rebuild the library from sources. You may show icons 

As a workaround, you may set the required color to  the '.mdl-textfield' class. 

PS: Sorry for this issue. I missed it since the class css.error.item is empty in standard version by default.
Thank you,
Andrew

**Comment by mattes3** [comment]
This error vanished after a "git pull" and rebuild from source. Thanks, Andrew!
